# Generated by Django 4.2 on 2026-08-15 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'تحت المعالجة'), ('closed', 'مغلق')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('rated_power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('customer_category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('model_version', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model_type', models.CharField(max_length=50)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecommendation',
            fields=[
                ('rec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.alert')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('forecast_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_date', models.DateField()),
                ('p10', models.FloatField()),
                ('p50', models.FloatField()),
                ('p90', models.FloatField()),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.modelregistry')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('reading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('power_kw', models.FloatField()),
                ('voltage', models.FloatField()),
                ('temperature', models.FloatField()),
                ('efficiency_ratio', models.FloatField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dashboard.household'),
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('detection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('composite_score', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.modelregistry')),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.devicereading')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.anomalydetection'),
        ),
    ]
